# 权重路径
weight_path: module/vgg16-397923af.pth

# 设备
device: cuda

# 图片格式
image_extensions:
  - .jpg
  - .png
  - .jpeg
  - .bmp
  - .webp

# 存放上传的图片数据
gallery_dir: upload

# 缩略图配置
thumbnail:
  # 大小
  size:
    height: 300
    width: 400

# 数据库配置
database:
  database_url: "sqlite+aiosqlite:///./database/image_search.db"
  echo: true
  pool_size: 10
  max_overflow: 20

# 分页查询每一页的数量
page_size: 20